### ISSUE TITLE
Body filter only loots everything

### ISSUE THREAD

**Issue by MxDeus** [fireundubh/fallout4#20]
Hi fireundubh, I absolutely love your mod, however it doesn't seem to loot through the filters e.g. ammo and caps and others, it just loots everything on a corpse, I have adjusted the filter option to any item.

Also I seem to get crash every time when there's a legendary items on a corpse, when my cursor points to the body the game just hangs, is there anything I'm doing wrong?

**Comment by fireundubh** [comment]
```
If dubhAutoLootTakeAll.Value == True
	objContainer.RemoveAllItems(kOtherContainer, dubhAutoLootTheftAlarm.Value)
Else
	LootObjectByFilter(dubhAutoLootFilterAll, dubhAutoLootPerks, objContainer, kOtherContainer)
EndIf
```

As you can see, there is no way for setting Filter Mode to Any Item to go wrong _unless_ the global variable (dubhAutoLootTakeAll) has been reset to its default value, which is True. It's literally a binary decision (this or that) for the script.

I would suggest toggling Filter Mode back to All Items and then again to Any Item.

> Also I seem to get crash every time when there's a legendary items on a corpse, when my cursor points to the body the game just hangs, is there anything I'm doing wrong?

Auto Loot cannot produce crashes. Crashes, especially like the one you're experiencing, are usually due to missing assets, such as meshes or textures. You may have installed another mod without all of its assets. Furthermore, it does no good to report crashes to me. I can do absolutely nothing about them, and I'll only ever respond as I'm doing now. Report crashes to Bethesda.

Finally, if you've ever uninstalled any mod during your current save, nobody can help you. Uninstalling mods is completely unsupported, and it'd be anyone's guess as to why something bad is happening.

**Comment by MxDeus** [comment]
Thank you for the quick reply! I will investigate further into the problem now, and keep up the good work!
