### ISSUE TITLE
Why the huge gimp?

### ISSUE THREAD

**Issue by Xetaxheb** [fireundubh/fallout4#22]
What's the purpose to removing the ranges and limiting the max filters?

**Comment by Xetaxheb** [comment]
And don't say performance, that's dumb. My PC ran it just fine with all filters on and tweaked heavily; including proc rates made faster in several of them. If people are dumb enough to turn on all the filters when they can't handle it, that's their problem, not yours. (not that this is any kind of real performance impact at all filters with 2048 range and 2 second proc. 8196 + immediate, may be a problem for overloaded load orders on midrange pc's.)

**Comment by fireundubh** [comment]
There are a few console commands you can use:

* Restore the removed ranges: `set dubhAutoLootDebugOptionsAvailable to 1`
* Allow use of any number of filters: `set dubhAutoLootTotalFiltersActive to 0` (or a negative number)

You have to run the latter command while you're in the Filters submenu.

Accessing the Filters submenu from the Main Menu resets that variable to the correct number.

Any Item mode was removed outright because it was incredibly slow. With all filters and Any Item mode, Auto Loot slowed to a crawl, and for some players, Auto Loot appeared to be doing nothing. While technically not my problem, I do receive constant feedback via e-mail and other sources.

If you want to revert to the previous version, you can do that with GitHub.

1. Go to [Commits](https://github.com/fireundubh/fallout4/commits/master/Auto%20Loot).
2. Click the hash for the [previous commit](https://github.com/fireundubh/fallout4/commit/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f#diff-49de51239f4ba9a09ba08388571493a5).
3. Click [Browse Files](https://github.com/fireundubh/fallout4/tree/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f).
4. Go to [Auto Loot](https://github.com/fireundubh/fallout4/tree/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f/Auto%20Loot).
5. For the .esp and .ba2, click each file, right-click View Raw, and click "Save link as..."

**Comment by Xetaxheb** [comment]
Works for me, though I still feel it would be better to have these options in the menu (even under debug toggles) for those not ~console savvy. (or xbox/playstation users that don't run many mods, not that _I_ care about that platform)

**Comment by Occams-Cat** [comment]
Well, that's a bummer, a lot of the functionality has been removed with the new update.
I had mine set to 2048 range, and LOVED listening to "swish, clank, swoop, clink, swish, clank" as I auto looted an entire building upon entering it.

I don't understand how removing the OPTIONS and making them limited is solved anything, while it's made some people happy, who obviously don't even bother going into the settings and customizing Auto Loot, it's completely removed any CHOICES the rest of us had for what our systems or Preferences were for the mod.

A pretty drastic, and unfortunate change all around.

Perhaps a better, less draconian solution for the people who think "the mod isn't working" is to bring back all of the features that were removed, but also add a "PRESETS" page where less-experienced users who can't be bothered to "look under the hood" can just pick Presets like "Fast and short range", "Fast and Long range", Slower Long Range EVERYTHING" etc.

Sorry to say, but completely removing OPTIONS renders this mod kind of useless, and I ALWAYS use Auto Loot mods, (Except for Morrowind, because nobody has made one).

I will continue to use the version prior to this, as long as it will continue to work with any new version of Fallout 4, as I just can't see any point of using future versions that will be lacking any type of customization, features, or choices.

Thanks for the mod, and ENDORSED

**Comment by fireundubh** [comment]
Hmm, presets. That's a good solution. I'll think about it some more.

**Comment by fireundubh** [comment]
Here's a preview of upcoming changes:

```
DLC support:
- No longer requires Automatron and Far Harbor
- Accessing the Containers submenu will dynamically configure DLC support
- DLC submenu on Containers submenu will show only if you have Automatron or Far Harbor
- DLC settlements on DLC submenus will show only the available DLC settlements
- Loot Settlements toggle now works with DLC settlements

Holotape:
- Improved script that adds holotape to your inventory
- Added a menu option to a Vault 111 terminal that adds holotape to your inventory

UI:
- Restored 8192, 4096, and 2048 distance options for Windows and Xbox One
- Added warning to Distance submenu
- Added warning to Filters submenu

Audio:
- Silenced "I need to assign someone to this" sounds so the Flora filter is no longer annoying

Fixes:
- 128 distance option would appear as selected only when distance for All was used
- Auto Steal Mode: Only Owned toggle was not working

Maintenance:
- Refactored bodies and containers scripts
- Placed shared functions in library script
- Reduced script sizes overall

Other:
- Auto Loot no longer suspends while in combat
- Windows users can "set dubhAutoLootTakeAll to 0" to enable the Any Items filter mode (unsupported)

Known issues:
- Armor and weapons are not supported
- DLC-added items are not supported
```

Haven't got around to presets yet, or a combat toggle. This dynamic DLC support thing is a monster.

**Comment by Occams-Cat** [comment]
Thank you, I appreciate you at least listening to my suggestions and possibly considering them.
I was initially concerned that I may have come across too negatively, but am just hoping to bring back original functionality, for people along with suggesting how to provide a solution for other users who don't care as much about "looking under the hood"

Also, a HUGE thank you for the "I need to assign someone to this" it was driving me crazy, I at first thought that a settler mod I was using was the culprit.
I was using your "Silent Loot" mod but I deleted the sound references in the ESP because I LIKED hearing all the stuff getting looted (it let me know it was doing it's job, and it was fun to listen to)

**Comment by Xetaxheb** [comment]
I'm thoroughly excited by these upcoming changes, I hope weapons and armor aren't super far down the line, though honestly I don't feel they're as high a priority as presets. Presets are useless to me but will probably save you a lot of (uninformed) comments about performance issues.

**Comment by fireundubh** [comment]
> Also, do you need a list of the objects/flora in Far Harbor?

My dynamic DLC support thing seems to be working, so yeah.

**Comment by Occams-Cat** [comment]
That all sounds very complicated.

**Comment by fireundubh** [comment]
It's a lot more work than I let on! But it should be much simpler to maintain going forward.

**Comment by Occams-Cat** [comment]
This is why I only make textures lol

**Comment by fireundubh** [comment]
Just an update: Most of the work is done. What's left is just updating the holotape terminals.

I deleted a number of unused records, and infrequently used features (e.g., debug proc rates), to cut down the workload. In doing so though, I ended up renumbering every record, which invalidated all of the terminal fragment scripts. Fortunately, redoing them is straightforward and much easier now, but it's a pretty boring affair and there are 81 terminals, so I'll have to find some time to just do it.

As an aside, fragments are stupid and totally unnecessary. Not sure why Bethesda had that bright idea.

**Comment by Occams-Cat** [comment]
Because Bethesda
lol

**Comment by fireundubh** [comment]
Also, this is what it's like to maintain this mod for consoles: http://imgur.com/a/wB2UO. So, not exactly encouraging.

**Comment by Occams-Cat** [comment]
got a 404 on that link

**Comment by fireundubh** [comment]
Did you copy the link with the period at the end?

**Comment by Occams-Cat** [comment]
yea, with the period and without the period, even clicked on it, I get the "Whoops took a wrong turn" imgur page

**Comment by fireundubh** [comment]
Oh, I had the privacy settings wrong. It works now.

**Comment by Occams-Cat** [comment]
Good lord, what a bunch of thankless people.
No wonder your mod is only on github.
This mod was the reason I actually used Bethesda.net to download for my PC ONCE.
But it looks like you're damned if you do and damned if you don't

**Comment by Dadditude** [comment]
I'm just grateful that you are still willing to support the consoles in spite of the idiots. I just wish Bethesda would give us a way to flag comments as inappropriate/harassing so that mod authors and community members can do something about these trolls. Really looking forward to the next release!

**Comment by Dadditude** [comment]
Ack! Did you pull your mods from Bethesda.net? They're not showing up in search results anymore!

**Comment by phuhque** [comment]
@Dadditude I think it was because Bethesda was being a dick.  Lots of authors got their mods removed.  I do feel sorry for console owners since it is Bethesda that has final say on what they can install.  It would be really cool if something like Nexus could be implemented for the Xbox and Playstation consoles.

I haven't played Fallout in over a month now, but this was one of my "essential" mods and even with the challenges, it is among my favorites.

**Comment by Occams-Cat** [comment]
Just look at the screenshot he posted in this thread.
It wasn't bethesda being a dick

**Comment by fireundubh** [comment]
> Ack! Did you pull your mods from Bethesda.net? They're not showing up in search results anymore!

Yup. It is unfortunate that Bethesda routed console mods through a haphazardly designed platform, dominated by a loud toxic minority, and now moderated by volunteers on power trips. Bethesda.net has become extremely unfriendly for modders. They were already unfriendly to boot. A few months ago, they removed all of my mods, which had many tens of thousands of subscribers on PC, merely because they were on a schedule and did not want to do things the right way. Bethesda did apologize, but the writing was on the wall then.

Many of the best known modders are avoiding the platform due to the lack of moderation tools and the company's attitude toward protecting the intellectual property interests of modders. The Nexus has even [come out against Bethesda.net](http://www.nexusmods.com/skyrim/news/12815). Furthermore, I could also tell from the lack of traffic to the re-uploaded PC versions of my mods that PC players are avoiding Bethesda.net, too. So, I just don't see any benefit to toughing out what is a very bad situation, and when I have a choice about dealing with frustrating circumstances and people, I'm going to choose my sanity every time.

If you're a console-only player, I'm sorry that my mods are now out of reach for you.

**Comment by Xetaxheb** [comment]
I don't and will never play bethesda games on console (or even get any of the current or last gen ones except maybe eventually when they're 50$ on craigslist for a few exclusives) and while I respect your right to do as you please with your content (like you deleting your nexus account) 
I'm disappointed that you don't feel uploading the mod to beth.net (I do not USE beth.net) and updating it every now and then while completely ignoring the comment section is an option. This would let the sane and mature people use your mod on consoles.

Anyone who isn't a dick and is having actual bug issues that aren't just "consoles are underpowered", eventually one of them will have the brain to make their way here to report the issue.
I don't think the toxic part of the community will make their way here, and it's simple to block them from commenting if they do. 

I haven't bought a console since 06 but I know a little bit about how files get on them, and realistically it would be an enormous pain in the ass to get them on the hdd (I don't think xbone or ps4 have filesystem access tools yet), let alone if (console) FO4 even will load files without them being enabled in beth.net.

**Comment by phuhque** [comment]
Sorry, I rarely notice text that uses inline colors.  For me it's a hue thing.  I went and read it and do agree.  Everyone was pretty much negative (and that is something coming from me.  I am always negative)  Personally I don't like the integrated mod system Bethesda has anyway, so my descriptive definition still applies to them.  Their content censorship is enough to repel anyone, player and modder alike.  The only reason I even tried to use their service is because AutoLoot became their exclusive.  Now that is no longer there, I don't even consider looking.  Honestly not worth my time.  Even if they had "the perfect mod" I would not be going there to get it.

@fireundubh Keep up the good work and I appreciate the effort you continue to put into your mods to make my game more enjoyable.

**Comment by fireundubh** [comment]
> while completely ignoring the comment section is an option.

It wasn't a real option though. I don't want mindless comments to affect mindful users, which they will, do, and did.

From [Popular Science: Why We're Shutting Off Our Comments](http://www.popsci.com/science/article/2013-09/why-were-shutting-our-comments):

> [...] even a fractious minority wields enough power to skew a reader's perception of a story, recent research suggests. In one study led by University of Wisconsin-Madison professor Dominique Brossard, 1,183 Americans read a fake blog post on nanotechnology and revealed in survey questions how they felt about the subject (are they wary of the benefits or supportive?).

> Then, through a randomly assigned condition, they read either epithet- and insult-laden comments ("If you don't see the benefits of using nanotechnology in these kinds of products, you're an idiot" ) or civil comments. The results, as Brossard and coauthor Dietram A. Scheufele wrote in a New York Times op-ed:

> **Uncivil comments not only polarized readers, but they often changed a participant's interpretation of the news story itself.**

> In the civil group, those who initially did or did not support the technology — whom we identified with preliminary survey questions — continued to feel the same way after reading the comments. Those exposed to rude comments, however, ended up with a much more polarized understanding of the risks connected with the technology.

> Simply including an ad hominem attack in a reader comment was enough to make study participants think the downside of the reported technology was greater than they'd previously thought.

Riot Games has done a lot of work in this area as well. See:

* [The science behind shaping behavior in online games](http://gdcvault.com/play/1017940/The-Science-Behind-Shaping-Player) (presentation, conference recording)
* [Assessing toxicity in the workplace](https://rework.withgoogle.com/case-studies/riot-games-assessing-toxicity/) (employee dismissals correlated with toxic behavior in League of Legends chat)

When unhindered, toxic behavior proliferates. It isn't enough for folks like you to stand up against trolls. Although it is nice to see, that article in Popular Science says that fighting trolls in the comments just makes things worse.

> Another similarly designed study found that just firmly worded (but not uncivil) disagreements between commenters impacted readers' perception of science.

Modders need to be able to control their subcommunities (mod pages), hide comments, mute toxic users, and lock down comments. Unfortunately, when I suggested this in the Creation Kit forum, a volunteer Bethesda.net moderator closed the thread. So, without that control, there's really no point to anyone whose mods receive a lot of traffic and feedback in trying to weather a storm that can only grow in power.

**Comment by Occams-Cat** [comment]
Interesting article, and that's EXACTLY why I have to avoid reading any comments when I click on a news article from MSN, the comment sections on MSN articles are toxic and infuriating.

I also had to shut down my facebook account a couple of months ago, because of that stupid "trending" thing they have.
Because it's always top news stories about politics etc, and inevitably someone on my friends list would comment on one or many articles, and that spams them to EVERYBODY'S wall that the person is friends with.

Too many times I found myself pissing a night away arguing with people who didn't care about facts or truth and they would just start name-calling etc, and 99% of the time it would end up being a scripted argument copy & paste war. Someone would copy & paste an old tired argument, and it was easy to use the same old tired counterargument, and inevitably would come the counter-counter-argument to the response etc ad infinitum.

If facebook wants to inspire strangers to make contact with each other and become friends, they need to do away with that poisonous feature 
I got so damned sick of it I had to leave, it wasn't productive. While I was able to stay in contact with family and friends up north, I also ended up with all this verbal sewage all over my wall.

**Comment by Occams-Cat** [comment]
Also interesting, YOUR Modding question thread got shut down, yet people are allowed to continue to do and say whatever they please in a mod comment section

**Comment by Xetaxheb** [comment]
@Occams-Cat Different forums moderated by different people

@fireundubh 
> It wasn't a real option though. I don't want mindless comments to affect mindful users, which they will, do, and did.

I definitely understand what you are saying, but what I'm trying to get across is "just leave it up so the people who want it can get it". 0% can if you take it down, more than that even if toxic comments turn a couple % off from what it would be if you moderated it. 

Don't let "a few bad apples" drag the rest of the users down by turning it off.

(though who am I kidding, probably 75%+ of console users aka people who can't afford a computer are kiddies using daddies credit card and are toxic little shits.)

Again, I have no stake in this, but I do feel it'd be better to leave it accessible even if unsupported.
That's the end of my thoughts on this matter.

**Comment by fireundubh** [comment]
Since I've answered the question in the original post, I'll close the issue.

If anyone here has other feedback, please create a new issue.

Thank you.
