### ISSUE TITLE
How do I loot only some items from bodies and containers?

### ISSUE THREAD

**Issue by DwellerV13** [fireundubh/fallout4#28]
First of all, thank you for this amazing mod. Fallout 4 is a lot more enjoyable when you don't have to worry about picking everything up.

However, I read this in the mod page: "Control whether you take everything from bodies and containers, or just some things" and was wondering how do I do that? I tried configuring the mod, but everything in bodies and containers always get looted.

**Comment by fireundubh** [comment]
Filter Mode was removed because the game is not designed for inventory to be iterated over in the way that Auto Loot makes possible _without_ hacks or script extenders. Filter Mode could be extremely slow, delaying the looting of items by seconds or giving users the impression that nothing was happening. Furthermore, Filter Mode was hard to understand for enough users that I simply grew tired of answering questions about it.

If you want to revert to the previous version, you can do that with GitHub.

1. Go to [Commits](https://github.com/fireundubh/fallout4/commits/master/Auto%20Loot).
2. Click the hash for the [previous commit](https://github.com/fireundubh/fallout4/commit/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f#diff-49de51239f4ba9a09ba08388571493a5).
3. Click [Browse Files](https://github.com/fireundubh/fallout4/tree/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f).
4. Go to [Auto Loot](https://github.com/fireundubh/fallout4/tree/7f8581f2df965a6eebc8c2c28b2a78a46a174b9f/Auto%20Loot).
5. For the .esp and .ba2, click each file, right-click View Raw, and click "Save link as..."

**Comment by DwellerV13** [comment]
Oh, ok. I'll test the old version and see if I like it. Otherwise, I'll just stick with the new one.

Thanks!
