### ISSUE TITLE
Interactive Clutter Not auto looting

### ISSUE THREAD

**Issue by lordzues40** [fireundubh/fallout4#32]
I have both your auto loot and Interactive clutter but noticed that the Interactive clutter does not auto looting. plus in sanctuary the clutter responds rather quickly even while i am in the settlement.
So i was wondering if the clutter is suppose to respon at all.

**Comment by fireundubh** [comment]
I have no idea what you're trying to tell me. Please correct your English. Thank you.

**Comment by lordzues40** [comment]
Your interactive clutter does not work with your auto loot. Also in sanctuary the interactive clutter respawns. It even does it without leaving the settlement

**Comment by fireundubh** [comment]
That's probably true. I never released a plugin that adds the Interactive Clutter forms to Auto Loot, partly because there are some clutter items that should not be picked up or moved, such as barrels that have a static object on top. One day I'll get around to sorting those issues out, but Interactive Clutter should be considered very experimental for the time being.

**Comment by lordzues40** [comment]
As far as the barrels, why not just exclude them?  
Any idea why the interactive clutter is respawning in sanctuary? I really haven't paid attention elsewhere just noticed it in sanctuary. I plan on starting a new game when nucka world comes out and do some more testing. Just thought while I was waiting I'd give you a shout and pick your brain a Lil. I totally love your mods. Like I said before I have auto loot, interactive clutter, and auto lockpick. Only other issue is can see is with auto lockpick you don't get any reputation gains with Cait. All the followers still comment on junk pickup just not on the auto lockpick.

**Comment by fireundubh** [comment]
> As far as the barrels, why not just exclude them?

Interactive Clutter changes 25,000+ references.

A few references shouldn't be changed, but that's no reason to exclude a ton of references that should be.

The mod requires some fine-tuning of the xEdit script that generates it. I have to write an algorithm that can detect whether an object has an object too close to it based purely on X/Y/Z positioning data. But I haven't had time to dive back into modding.

> Any idea why the interactive clutter is respawning in sanctuary?

I'm not really sure how settlements are set up anymore. They might be set to respawn everything, which would include clutter.

> I plan on starting a new game when nucka world comes out and do some more testing.

Interactive Clutter will have no impact on objects placed in Nuka World.

> Only other issue is can see is with auto lockpick you don't get any reputation gains with Cait. 

I might be able to put out a fix for this since it sounds simple enough. Maybe. No promises. Started a new job!

**Comment by lordzues40** [comment]
Hey I totally understand about not having time, the fact that you took the time to address my comments is "A Job Well Done" in my book. 

I didn't expect interactive clutter would have any impact on nucka world I was simply stating that I was waiting for nucka world before starting a new game the last update broke my save for some reason so I decided to go through all my mods and cull, rearrange, update and so on and so forth.

**Comment by lordzues40** [comment]
(Stupid phone)  
Anyway just wanted to say great mods (again) and keep up the good work. Every thing you do is truly appreciated at least by one person. 

Oh oh before I forget again the interactive clutter IS compatible with "manufacturing extended" although you have to pick and choose what to run through the machine, sense some things won't fit  in the machine  or when they spawn on the conveyor belt, some objects can get stuck in the opening of the vacuum machine. But to tell ya it is very pleasing and satisfying to watch wooden boxes, tires, plastic trays, and other junk move down the belts to the recycler.
